// The runtime dependencies passed to generated AOT functions via factory arguments
import { Env, ErrorObject, IProcedure, MissingVarError, MultipleValues, VMError, packValues } from "../common";
import { Caught, ContinuationMarkSet, EXCEPTION_HANDLERS, Handlers, markFirst, markSet, recordTailMark } from "../marks";
import { CaseLambda, Closure } from "./code";
import { ControlRequest, HostTail, applyArgs, applyIntrinsic, arrayArg, catchGuard, raiseContinuable, stackSkip } from "./coreops";
import {
    Box,
    CatchToken,
    EscapeContinuation,
    Frame,
    errorPos,
    InterruptError,
    MAX_JS_DEPTH,
    MAX_NESTED_RESUMES,
    MISSING,
    MULTI,
    StackSnapshot,
    Suspend,
    WindPoint,
    catchHere,
    caughtAt,
    countControlSuspend,
    frameInfos,
    oneValue,
    restValues,
    tailName,
    unpackForBinding,
    unwind,
    VB,
    manyValues,
} from "./values";

export const JIT_DEPS = {
    markSet,
    recordTailMark,
    tailName,
    ContinuationMarkSet,
    MultipleValues,
    unpackForBinding,
    restValues,
    oneValue,
    MULTI,
    VB,
    manyValues,
    IProcedure,
    ErrorObject,
    Box,
    MissingVarError,
    VMError,
    errorPos,
    unwind,
    Closure,
    CaseLambda,
    WindPoint,
    applyArgs,
    arrayArg,
    raiseContinuable,
    catchGuard,
    stackSkip,
    packValues,
    Handlers,
    MISSING,
    MAX_JS_DEPTH,
    MAX_NESTED_RESUMES,
    Env,
    Frame,
    Suspend,
    InterruptError,
    EscapeContinuation,
    countControlSuspend,
    StackSnapshot,
    frameInfos,
    HostTail,
    ControlRequest,
    applyIntrinsic,
    CatchToken,
    Caught,
    catchHere,
    caughtAt,
    markFirst,
    EXCEPTION_HANDLERS,
};
