// Lambda lifting, a pass over the core forms before analysis. A lambda bound by a %letrec whose name is never assigned
// and only ever called (so every call is known) gets its free local variables as extra parameters, passed by every call,
// so it captures nothing and compiles to a constant closure: none is made each time the %letrec runs. The variables
// passed include the lifted lambdas it calls (itself too, if it recurses), which it receives as values, and those its
// callees need. A free variable that is assigned anywhere stops the lifting (a copy would miss the assignments)
// This entire file was generated by Claude Opus 5.5, as was the argument for its correctness in PROOFS.md (1-3); neither
// has been independently verified
import { CORE_BLOCK, CORE_CALL, CORE_ESCAPE, CORE_INTCALL, CORE_LAMBDA, CORE_LET, CORE_LET_STAR, CORE_LETREC, CORE_SET } from "../common";
import { Lsrc, parts as partsOf, withBounds, type Parts } from "./passes/lang";

import { accepts, bodyOf, clause, clausesOf, isLambda, isSingleLambda, optionsOf, paramsOf, restOf, type Clause } from "./lambda";

// the clause of a %lambda of one (see lambda.ts)
const only = (lambda: any[]): Clause => lambda[2];

const parts = (e: any[]): Parts => partsOf(Lsrc, e);

// every name %set! assigns anywhere in `e`
const assignedNames = (e: any, out: Set<symbol> = new Set()): Set<symbol> => {
    if (!Array.isArray(e)) return out;
    if (e[0] === CORE_SET) out.add(e[2]);
    for (const [x] of parts(e).exprs) assignedNames(x, out);
    return out;
};

// whether `e` is a call of `name`
const isCallOf = (e: any, name: symbol): boolean => Array.isArray(e) && e[0] === CORE_CALL && e[2] === name;

// Locals have names of their own (the rename pass), so a name is never shadowed: a use of it anywhere is a use of the
// one variable

// The uses of `name` in `e`: its calls, and whether it is used any other way
type Uses = { calls: any[][], other: boolean };
const usesOf = (e: any, name: symbol, out: Uses = { calls: [], other: false }): Uses => {
    if (e === name) {
        out.other = true;
        return out;
    }
    if (!Array.isArray(e)) return out;
    if (e[0] === CORE_SET && e[2] === name) out.other = true;
    parts(e).exprs.forEach(([x], i) => {
        if (i === 0 && isCallOf(e, name)) out.calls.push(e);
        else usesOf(x, name, out);
    });
    return out;
};

// the names of `scope` used in `e`
const freeIn = (e: any, scope: ReadonlySet<symbol>, out: Set<symbol>): Set<symbol> => {
    if (typeof e === "symbol") {
        if (scope.has(e)) out.add(e);
        return out;
    }
    if (!Array.isArray(e)) return out;
    for (const [x] of parts(e).exprs) freeIn(x, scope, out);
    return out;
};

// `e` with the uses of the names in `map` replaced, and the calls in `extra` given their extra arguments
const rewrite = (e: any, map: ReadonlyMap<symbol, symbol>, extra: ReadonlyMap<any[], symbol[]>): any => {
    if (typeof e === "symbol") return map.get(e) ?? e;
    if (!Array.isArray(e)) return e;
    const p = partsOf(Lsrc, e);
    const next = p.exprs.map(([x]) => rewrite(x, map, extra));
    const added = extra.get(e);
    if (added === undefined) return p.rebuild(next);
    return [CORE_CALL, e[1], next[0], ...added.map(a => map.get(a) ?? a), ...next.slice(1)];
};

// `e` with the calls in `map` calling the name given for them instead
const replaceCalls = (e: any, map: ReadonlyMap<any[], symbol>): any => {
    if (!Array.isArray(e) || map.size === 0) return e;
    const p = partsOf(Lsrc, e);
    const next = p.exprs.map(([x]) => replaceCalls(x, map));
    if (map.has(e)) next[0] = map.get(e);
    return p.rebuild(next);
};

const MAKE_CASE_LAMBDA = Symbol.for("%make-case-lambda");

// A %lambda of several clauses bound by a %let, %let* or %letrec to a name never assigned: each clause gets a name of its
// own (a %lambda of one, in a %letrec, so lifting applies to it), and every call of the name with a count a clause takes
// calls that clause. The procedure itself is only made (from the clauses, %make-case-lambda) if the name is still used
// some other way
export const splitCaseLambdas = (ast: any): any => {
    const assigned = assignedNames(ast);
    const isCandidate = (b: [symbol, any]) => isLambda(b[1]) && b[1].length > 3 && !assigned.has(b[0]);
    // the clauses of `name`'s case-lambda, the calls in `within` resolved to them, and whether the procedure is still needed
    const split = (name: symbol, caseLambda: any[], within: any[]) => {
        const clauses = clausesOf(caseLambda);
        const names = clauses.map(() => Symbol(name.description));
        const uses = within.reduce((u, x) => usesOf(x, name, u), { calls: [], other: false } as Uses);
        const map = new Map<any[], symbol>();
        let needed = uses.other;
        for (const node of uses.calls) {
            const i = clauses.findIndex(c => accepts(c, node.length - 3));
            if (i === -1) needed = true;
            else map.set(node, names[i]);
        }
        const bindings: [symbol, any][] = clauses.map((c, i) => [names[i], [CORE_LAMBDA, caseLambda[1], c]]);
        const procedure: [symbol, any][] = needed ? [[name, [CORE_INTCALL, null, MAKE_CASE_LAMBDA, ...names]]] : [];
        return { bindings, procedure, map };
    };
    // `e`, a %let, %let* or %letrec whose inits and body are already done, with its candidates split
    const splitIn = (e: any[]): any[] => {
        const op = e[0];
        const bindings: [symbol, any][] = e[2];
        const at = bindings.findIndex(isCandidate);
        if (at === -1) return e;
        const [name, caseLambda] = bindings[at];
        const body = e.slice(3);
        // where the name is in scope: every init of a %letrec, the later ones of a %let*, and the body
        const within = op === CORE_LETREC ? [...bindings.map(b => b[1]), ...body]
            : op === CORE_LET_STAR ? [...bindings.slice(at + 1).map(b => b[1]), ...body]
            : body;
        const { bindings: clauses, procedure, map } = split(name, caseLambda, within);
        const fix = (x: any) => replaceCalls(x, map);
        if (op === CORE_LETREC) {
            const rest = bindings.filter((_, i) => i !== at).map(b => [b[0], fix(b[1])] as [symbol, any]);
            const own = clauses.map(([n, c]) => [n, fix(c)] as [symbol, any]);
            return splitIn([CORE_LETREC, e[1], [...rest.slice(0, at), ...own, ...procedure, ...rest.slice(at)], ...body.map(fix)]);
        }
        if (op === CORE_LET) {
            const rest = [...bindings.slice(0, at), ...procedure, ...bindings.slice(at + 1)];
            return [CORE_LETREC, e[1], clauses, splitIn([CORE_LET, null, rest, ...body.map(fix)])];
        }
        const after = [...procedure, ...bindings.slice(at + 1).map(b => [b[0], fix(b[1])] as [symbol, any])];
        const inner = [CORE_LETREC, at === 0 ? e[1] : null, clauses, splitIn([CORE_LET_STAR, null, after, ...body.map(fix)])];
        return at === 0 ? inner : [CORE_LET_STAR, e[1], bindings.slice(0, at), inner];
    };
    const walk = (e: any): any => {
        if (!Array.isArray(e)) return e;
        const p = parts(e);
        const done = p.rebuild(p.exprs.map(([x]) => walk(x)));
        return done[0] === CORE_LET || done[0] === CORE_LETREC || done[0] === CORE_LET_STAR ? splitIn(done) : done;
    };
    return walk(ast);
};

const CALL_EC = Symbol.for("%call/ec");
const CALL_CC = Symbol.for("%call/cc");
const VALUES = Symbol.for("%values");

// (%call/ec (%lambda (k) body ...)) or the same with %call/cc, where k is never assigned and only ever called in the
// body itself (not in a lambda inside it, nor passed on or kept as a value): k can then only be called while the call is
// still running, so every call of it is an escape out of the body, whichever continuation it is. The body becomes a
// %block and each (k v ...) an %escape to it, a jump. A continuation captured in the body and resumed later resumes the
// frame the block is in, so an escape there still lands where k would return to
export const blockEscapes = (ast: any): any => {
    const assigned = assignedNames(ast);
    // whether every use of k in e is a call outside any lambda
    const onlyCalled = (e: any, k: symbol, inLambda: boolean): boolean => {
        if (e === k) return false;
        if (!Array.isArray(e)) return true;
        const nested = inLambda || e[0] === CORE_LAMBDA;
        return parts(e).exprs.every(([x], i) => i === 0 && isCallOf(e, k) ? !nested : onlyCalled(x, k, nested));
    };
    const toEscapes = (e: any, k: symbol, label: symbol): any => {
        if (!Array.isArray(e)) return e;
        const p = parts(e);
        const next = p.exprs.map(([x]) => toEscapes(x, k, label));
        if (!isCallOf(e, k)) return p.rebuild(next);
        const args = next.slice(1);
        return [CORE_ESCAPE, e[1], label, args.length === 1 ? args[0] : [CORE_INTCALL, null, VALUES, ...args]];
    };
    const walk = (e: any): any => {
        if (!Array.isArray(e)) return e;
        const p = parts(e);
        const done = p.rebuild(p.exprs.map(([x]) => walk(x)));
        if (done[0] !== CORE_INTCALL || (done[2] !== CALL_EC && done[2] !== CALL_CC) || done.length !== 4) return done;
        const proc = done[3];
        if (!isSingleLambda(proc) || paramsOf(only(proc)).length !== 1 || restOf(only(proc)) !== null) return done;
        const k: symbol = paramsOf(only(proc))[0];
        const body = bodyOf(only(proc));
        if (assigned.has(k) || !body.every((x: any) => onlyCalled(x, k, false))) return done;
        const label = Symbol(k.description);
        return [CORE_BLOCK, done[1], label, ...body.map((x: any) => toEscapes(x, k, label))];
    };
    return walk(ast);
};

// the lifting itself (see the top of this file)
export const liftLambdas = (ast: any): any => {
    const assigned = assignedNames(ast);

    // `scope`: the local names bound around `e`. `unsafe`: those that may not have their value yet when code there runs
    // (%letrec values), which a copy would miss, so they cannot be passed
    const walk = (e: any, scope: ReadonlySet<symbol>, unsafe: ReadonlySet<symbol>): any => {
        if (!Array.isArray(e)) return e;
        if (e[0] === CORE_LETREC) {
            const bindings: [symbol, any][] = e[2];
            const names = bindings.map(b => b[0]);
            const lambdas = new Set(names.filter((_, i) => isSingleLambda(bindings[i][1])));
            const values = names.filter(n => !lambdas.has(n));
            // the values' inits run before some values have theirs; if they may run the lambdas, so may everything else
            const runsEarly = bindings.some(b => !isSingleLambda(b[1]) && freeIn(b[1], lambdas, new Set()).size > 0);
            const inner = new Set([...scope, ...names]);
            const inInits = new Set([...unsafe, ...values]);
            const afterInits = runsEarly ? inInits : unsafe;
            const next = bindings.map(b => [b[0], walk(b[1], inner, isSingleLambda(b[1]) ? afterInits : inInits)] as [symbol, any]);
            const body = e.slice(3).map((x: any) => walk(x, inner, afterInits));
            return liftIn([CORE_LETREC, e[1], next, ...body], scope, afterInits);
        }
        const p = parts(e);
        const next: any[] = [];
        for (const [x, around] of withBounds(p, scope)) next.push(walk(x, around, unsafe));
        return p.rebuild(next);
    };

    const liftIn = (letrec: any[], outer: ReadonlySet<symbol>, unsafe: ReadonlySet<symbol>): any[] => {
        const bindings: [symbol, any][] = letrec[2];
        const body = letrec.slice(3);
        const names = bindings.map(b => b[0]);
        const scope = new Set([...outer, ...names]);
        const inits = new Map<symbol, any>(bindings);
        const within = [...bindings.map(b => b[1]), ...body];

        let lifted = new Set(names.filter(n => isSingleLambda(inits.get(n)) && !assigned.has(n)));
        let fv = new Map<symbol, symbol[]>();
        let calls = new Map<symbol, Uses["calls"]>();
        for (;;) {
            calls = new Map();
            const next = new Set<symbol>();
            for (const name of lifted) {
                const uses = within.reduce((u, x) => usesOf(x, name, u), { calls: [], other: false } as Uses);
                if (uses.other || uses.calls.some((c: any[]) => !accepts(only(inits.get(name)), c.length - 3))) continue;
                next.add(name);
                calls.set(name, uses.calls);
            }
            // what each passes: its free locals (lifted ones it calls included), then what those need, to a fixpoint
            fv = new Map([...next].map(name => {
                const c = only(inits.get(name));
                const free = new Set<symbol>();
                for (const x of bodyOf(c)) freeIn(x, scope, free);
                return [name, [...free]];
            }));
            for (let changed = true; changed;) {
                changed = false;
                for (const vars of fv.values()) {
                    for (const v of [...vars]) {
                        for (const w of fv.get(v) ?? []) {
                            if (!vars.includes(w)) {
                                vars.push(w);
                                changed = true;
                            }
                        }
                    }
                }
            }
            // an assigned or not yet known variable cannot be passed, and a call must see the variables it passes as they are here
            for (const name of [...next]) {
                const vars = fv.get(name)!;
                if (vars.some(v => assigned.has(v) || unsafe.has(v))) next.delete(name);
            }
            if (next.size === lifted.size) break;
            lifted = next;
        }
        if (lifted.size === 0) return letrec;

        const extra = new Map<any[], symbol[]>();
        for (const name of lifted) for (const c of calls.get(name)!) extra.set(c, fv.get(name)!);
        const liftedInit = (name: symbol): any[] => {
            const lambda = inits.get(name);
            const c = only(lambda);
            const vars = fv.get(name)!;
            const renamed = new Map(vars.map(v => [v, Symbol(v.description)]));
            const newBody = bodyOf(c).map((x: any) => rewrite(x, renamed, extra));
            return [CORE_LAMBDA, lambda[1], clause(optionsOf(c), [...vars.map(v => renamed.get(v)!), ...paramsOf(c)], restOf(c), newBody)];
        };
        const newBindings = bindings.map(b => [b[0], lifted.has(b[0]) ? liftedInit(b[0]) : rewrite(b[1], new Map(), extra)]);
        const newBody = body.map(x => rewrite(x, new Map(), extra));
        return [CORE_LETREC, letrec[1], newBindings, ...newBody];
    };

    return walk(ast, new Set(), new Set());
};
