// Lambda lifting, a pass over the core forms before analysis. A lambda bound by a %letrec whose name is never assigned
// and only ever called (so every call is known) gets its free local variables as extra parameters, passed by every call,
// so it captures nothing and compiles to a constant closure: none is made each time the %letrec runs. The variables
// passed include the lifted lambdas it calls (itself too, if it recurses), which it receives as values, and those its
// callees need. A free variable that is assigned anywhere stops the lifting (a copy would miss the assignments)
// This entire file was generated by Claude Opus 5.5, as was the argument for its correctness in PROOFS.md (1-3); neither
// has been independently verified
import { CORE_BLOCK, CORE_ESCAPE, CORE_LAMBDA, CORE_LET, CORE_LET_STAR, CORE_LET_VALUES, CORE_LET_VALUES_STRICT, CORE_LETREC, CORE_QUOTE, CORE_SET, OP_DEFINE_GLOBAL, SOURCE_POS } from "../common";

import { accepts, bodyOf, clause, clausesOf, isLambda, isSingleLambda, namesOf, optionsOf, paramsOf, restOf, type Clause } from "./lambda";

const keepPos = <T>(to: T, from: any): T => {
    const pos = SOURCE_POS.get(from);
    if (pos !== undefined && Array.isArray(to)) SOURCE_POS.set(to, pos);
    return to;
};

// the clause of a %lambda of one (see lambda.ts)
const only = (lambda: any[]): Clause => lambda[1];

// Each expression position in `e` with the names bound around it (beyond those around `e`), and how to rebuild `e`
// from new expressions for them. Block labels and the names %set! / %define-global assign are not expressions. For a
// %let* (`seq`), each position's names add to those of the positions before it (see withBounds)
type Parts = { exprs: [any, symbol[]][], rebuild: (next: any[]) => any, seq?: boolean };
const parts = (e: any[]): Parts => {
    const same = (exprs: [any, symbol[]][], rebuild: (next: any[]) => any): Parts => ({ exprs, rebuild: next => keepPos(rebuild(next), e) });
    const op = e[0];
    switch (op) {
        case CORE_QUOTE:
            return { exprs: [], rebuild: () => e };
        case CORE_LAMBDA: {
            const clauses = clausesOf(e);
            const exprs = clauses.flatMap(c => bodyOf(c).map(x => [x, namesOf(c)] as [any, symbol[]]));
            return same(exprs, next => {
                let at = 0;
                return [CORE_LAMBDA, ...clauses.map(c => {
                    const n = c.length - 3;
                    at += n;
                    return [c[0], c[1], c[2], ...next.slice(at - n, at)];
                })];
            });
        }
        case CORE_LET:
        case CORE_LETREC: {
            const bindings: [symbol, any][] = e[1];
            const names = bindings.map(b => b[0]);
            const inner = op === CORE_LETREC ? names : [];
            return same([...bindings.map(b => [b[1], inner] as [any, symbol[]]), ...e.slice(2).map(x => [x, names] as [any, symbol[]])], next =>
                [op, bindings.map((b, i) => keepPos([b[0], next[i]], b)), ...next.slice(bindings.length)]);
        }
        case CORE_LET_STAR: {
            const bindings: [symbol, any][] = e[1];
            const body = e.slice(2);
            const exprs: [any, symbol[]][] = [
                ...bindings.map((b, i) => [b[1], i === 0 ? [] : [bindings[i - 1][0]]] as [any, symbol[]]),
                ...body.map((x, i) => [x, i === 0 && bindings.length > 0 ? [bindings[bindings.length - 1][0]] : []] as [any, symbol[]]),
            ];
            return { exprs, seq: true, rebuild: next => keepPos([op, bindings.map((b, i) => keepPos([b[0], next[i]], b)), ...next.slice(bindings.length)], e) };
        }
        case CORE_LET_VALUES:
        case CORE_LET_VALUES_STRICT: {
            const clauses: [symbol[], symbol | null, any][] = e[1];
            const names = clauses.flatMap(c => c[1] === null ? c[0] : [...c[0], c[1]]);
            return same([...clauses.map(c => [c[2], []] as [any, symbol[]]), ...e.slice(2).map(x => [x, names] as [any, symbol[]])], next =>
                [op, clauses.map((c, i) => [c[0], c[1], next[i]]), ...next.slice(clauses.length)]);
        }
        case CORE_SET:
        case OP_DEFINE_GLOBAL:
            return same([[e[2], []]], next => [op, e[1], next[0]]);
        case CORE_BLOCK:
        case CORE_ESCAPE:
            return same(e.slice(2).map(x => [x, []]), next => [op, e[1], ...next]);
        default:
            return same(e.map(x => [x, []]), next => next);
    }
};

// each expression position of `p` with the names bound around it, given those around the form (`bound`, not changed).
// A %let*'s positions share one growing set, so a long one costs no more than its length
function* withBounds(p: Parts, bound: ReadonlySet<symbol>): Generator<[any, ReadonlySet<symbol>]> {
    if (p.seq) {
        const running = new Set(bound);
        for (const [x, added] of p.exprs) {
            for (const name of added) running.add(name);
            yield [x, running];
        }
        return;
    }
    for (const [x, names] of p.exprs) yield [x, names.length === 0 ? bound : new Set([...bound, ...names])];
}

// every name %set! assigns anywhere in `e`
const assignedNames = (e: any, out: Set<symbol> = new Set()): Set<symbol> => {
    if (!Array.isArray(e)) return out;
    if (e[0] === CORE_SET) out.add(e[1]);
    for (const [x] of parts(e).exprs) assignedNames(x, out);
    return out;
};

const FORMS = new Set([CORE_QUOTE, CORE_LAMBDA, CORE_LET, CORE_LET_STAR, CORE_LETREC, CORE_LET_VALUES, CORE_LET_VALUES_STRICT, CORE_SET, OP_DEFINE_GLOBAL, CORE_BLOCK, CORE_ESCAPE]);

// The unshadowed uses of `name` in `e`: calls (with the names bound between `e` and each call, unless the call is inside
// one of `skip`, the lifted lambdas, which rename what they need), and whether it is used any other way
type Uses = { calls: { node: any[], bound: ReadonlySet<symbol> }[], other: boolean };
const usesOf = (e: any, name: symbol, skip: ReadonlySet<any>, bound: ReadonlySet<symbol> = new Set(), out: Uses = { calls: [], other: false }, inSkip = false): Uses => {
    if (e === name) {
        out.other = true;
        return out;
    }
    if (!Array.isArray(e)) return out;
    if (e[0] === CORE_SET && e[1] === name) out.other = true;
    const inner = inSkip || skip.has(e);
    let i = 0;
    for (const [x, around] of withBounds(parts(e), bound)) {
        if (!around.has(name)) {
            // the operator of a call
            if (i === 0 && x === name && e[0] === name && !FORMS.has(e[0])) out.calls.push({ node: e, bound: inner ? new Set() : new Set(bound) });
            else usesOf(x, name, skip, around, out, inner);
        }
        i++;
    }
    return out;
};

// the names of `scope` used (unshadowed) in `e`
const freeIn = (e: any, scope: ReadonlySet<symbol>, bound: ReadonlySet<symbol>, out: Set<symbol>): Set<symbol> => {
    if (typeof e === "symbol") {
        if (scope.has(e) && !bound.has(e)) out.add(e);
        return out;
    }
    if (!Array.isArray(e)) return out;
    for (const [x, around] of withBounds(parts(e), bound)) freeIn(x, scope, around, out);
    return out;
};

// `e` with the unshadowed free uses of the names in `map` replaced, and the calls in `extra` given their extra arguments
const rewrite = (e: any, map: ReadonlyMap<symbol, symbol>, extra: ReadonlyMap<any[], symbol[]>, bound: ReadonlySet<symbol> = new Set()): any => {
    if (typeof e === "symbol") return !bound.has(e) && map.get(e) || e;
    if (!Array.isArray(e)) return e;
    const p = parts(e);
    const next: any[] = [];
    for (const [x, around] of withBounds(p, bound)) next.push(rewrite(x, map, extra, around));
    const added = extra.get(e);
    if (added === undefined) return p.rebuild(next);
    // inside a lifted lambda these are its fresh parameters, which nothing shadows
    return keepPos([next[0], ...added.map(a => map.get(a) ?? a), ...next.slice(1)], e);
};

// `e` with the calls in `map` calling the name given for them instead
const replaceCalls = (e: any, map: ReadonlyMap<any[], symbol>): any => {
    if (!Array.isArray(e) || map.size === 0) return e;
    const p = parts(e);
    const next = p.exprs.map(([x]) => replaceCalls(x, map));
    const to = map.get(e);
    if (to !== undefined) next[0] = to;
    return p.rebuild(next);
};

const MAKE_CASE_LAMBDA = Symbol.for("%make-case-lambda");

// A %lambda of several clauses bound by a %let, %let* or %letrec to a name never assigned: each clause gets a name of its
// own (a %lambda of one, in a %letrec, so lifting applies to it), and every call of the name with a count a clause takes
// calls that clause. The procedure itself is only made (from the clauses, %make-case-lambda) if the name is still used
// some other way
const splitCaseLambdas = (ast: any, assigned: ReadonlySet<symbol>): any => {
    const isCandidate = (b: [symbol, any]) => isLambda(b[1]) && b[1].length > 2 && !assigned.has(b[0]);
    // the clauses of `name`'s case-lambda, the calls in `within` resolved to them, and whether the procedure is still needed
    const split = (name: symbol, caseLambda: any[], within: any[]) => {
        const clauses = clausesOf(caseLambda);
        const names = clauses.map(() => Symbol(name.description));
        const uses = within.reduce((u, x) => usesOf(x, name, new Set(), new Set(), u), { calls: [], other: false } as Uses);
        const map = new Map<any[], symbol>();
        let needed = uses.other;
        for (const { node } of uses.calls) {
            const i = clauses.findIndex(c => accepts(c, node.length - 1));
            if (i === -1) needed = true;
            else map.set(node, names[i]);
        }
        const bindings: [symbol, any][] = clauses.map((c, i) => [names[i], [CORE_LAMBDA, c]]);
        const procedure: [symbol, any][] = needed ? [[name, [MAKE_CASE_LAMBDA, ...names]]] : [];
        return { bindings, procedure, map };
    };
    // `e`, a %let, %let* or %letrec whose inits and body are already done, with its candidates split
    const splitIn = (e: any[]): any[] => {
        const op = e[0];
        const bindings: [symbol, any][] = e[1];
        const at = bindings.findIndex(isCandidate);
        if (at === -1) return e;
        const [name, caseLambda] = bindings[at];
        const body = e.slice(2);
        // where the name is in scope: every init of a %letrec, the later ones of a %let* (up to one binding it again, whose
        // init still sees it), and the body
        const again = op === CORE_LET_STAR ? bindings.findIndex((b, i) => i > at && b[0] === name) : -1;
        const within = op === CORE_LETREC ? [...bindings.map(b => b[1]), ...body]
            : op === CORE_LET_STAR ? (again === -1 ? [...bindings.slice(at + 1).map(b => b[1]), ...body] : bindings.slice(at + 1, again + 1).map(b => b[1]))
            : body;
        const { bindings: clauses, procedure, map } = split(name, caseLambda, within);
        const fix = (x: any) => replaceCalls(x, map);
        if (op === CORE_LETREC) {
            const rest = bindings.filter((_, i) => i !== at).map(b => keepPos([b[0], fix(b[1])], b));
            const own = clauses.map(([n, c]) => [n, fix(c)] as [symbol, any]);
            return splitIn(keepPos([CORE_LETREC, [...rest.slice(0, at), ...own, ...procedure, ...rest.slice(at)], ...body.map(fix)], e));
        }
        if (op === CORE_LET) {
            const rest = [...bindings.slice(0, at), ...procedure, ...bindings.slice(at + 1)];
            return keepPos([CORE_LETREC, clauses, splitIn([CORE_LET, rest, ...body.map(fix)])], e);
        }
        const after = [...procedure, ...bindings.slice(at + 1).map(b => keepPos([b[0], fix(b[1])], b))];
        const inner = [CORE_LETREC, clauses, splitIn([CORE_LET_STAR, after, ...body.map(fix)])];
        return keepPos(at === 0 ? inner : [CORE_LET_STAR, bindings.slice(0, at), inner], e);
    };
    const walk = (e: any): any => {
        if (!Array.isArray(e)) return e;
        const p = parts(e);
        const done = p.rebuild(p.exprs.map(([x]) => walk(x)));
        return done[0] === CORE_LET || done[0] === CORE_LETREC || done[0] === CORE_LET_STAR ? splitIn(done) : done;
    };
    return walk(ast);
};

const CALL_EC = Symbol.for("%call/ec");
const CALL_CC = Symbol.for("%call/cc");
const VALUES = Symbol.for("%values");

// (%call/ec (%lambda (k) body ...)) or the same with %call/cc, where k is never assigned and only ever called in the
// body itself (not in a lambda inside it, nor passed on or kept as a value): k can then only be called while the call is
// still running, so every call of it is an escape out of the body, whichever continuation it is. The body becomes a
// %block and each (k v ...) an %escape to it, a jump. A continuation captured in the body and resumed later resumes the
// frame the block is in, so an escape there still lands where k would return to
const blockEscapes = (ast: any, assigned: ReadonlySet<symbol>): any => {
    // whether every unshadowed use of k in e is a call outside any lambda
    const onlyCalled = (e: any, k: symbol, bound: ReadonlySet<symbol>, inLambda: boolean): boolean => {
        if (e === k) return false;
        if (!Array.isArray(e)) return true;
        const nested = inLambda || e[0] === CORE_LAMBDA;
        let i = 0;
        for (const [x, around] of withBounds(parts(e), bound)) {
            const operator = i++ === 0 && x === k && e[0] === k && !FORMS.has(e[0]);
            if (around.has(k)) continue;
            if (operator ? nested : !onlyCalled(x, k, around, nested)) return false;
        }
        return true;
    };
    const toEscapes = (e: any, k: symbol, label: symbol, bound: ReadonlySet<symbol>): any => {
        if (!Array.isArray(e)) return e;
        const p = parts(e);
        const next: any[] = [];
        for (const [x, around] of withBounds(p, bound)) next.push(around.has(k) ? x : toEscapes(x, k, label, around));
        if (e[0] !== k || FORMS.has(e[0]) || bound.has(k)) return p.rebuild(next);
        const args = next.slice(1);
        return keepPos([CORE_ESCAPE, label, args.length === 1 ? args[0] : [VALUES, ...args]], e);
    };
    const walk = (e: any): any => {
        if (!Array.isArray(e)) return e;
        const p = parts(e);
        const done = p.rebuild(p.exprs.map(([x]) => walk(x)));
        if ((done[0] !== CALL_EC && done[0] !== CALL_CC) || done.length !== 2) return done;
        const proc = done[1];
        if (!isSingleLambda(proc) || paramsOf(only(proc)).length !== 1 || restOf(only(proc)) !== null) return done;
        const k: symbol = paramsOf(only(proc))[0];
        const body = bodyOf(only(proc));
        if (assigned.has(k) || !body.every((x: any) => onlyCalled(x, k, new Set(), false))) return done;
        const label = Symbol(k.description);
        return keepPos([CORE_BLOCK, label, ...body.map((x: any) => toEscapes(x, k, label, new Set()))], done);
    };
    return walk(ast);
};

export const liftLambdas = (ast: any): any => {
    const assigned = assignedNames(ast);
    ast = blockEscapes(ast, assigned);
    ast = splitCaseLambdas(ast, assigned);

    // `scope`: the local names bound around `e`. `unsafe`: those that may not have their value yet when code there runs
    // (%letrec values), which a copy would miss, so they cannot be passed
    const walk = (e: any, scope: ReadonlySet<symbol>, unsafe: ReadonlySet<symbol>): any => {
        if (!Array.isArray(e)) return e;
        if (e[0] === CORE_LETREC) {
            const bindings: [symbol, any][] = e[1];
            const names = bindings.map(b => b[0]);
            const lambdas = new Set(names.filter((_, i) => isSingleLambda(bindings[i][1])));
            const values = names.filter(n => !lambdas.has(n));
            // the values' inits run before some values have theirs; if they may run the lambdas, so may everything else
            const runsEarly = bindings.some(b => !isSingleLambda(b[1]) && freeIn(b[1], lambdas, new Set(), new Set()).size > 0);
            const inner = new Set([...scope, ...names]);
            const inInits = new Set([...unsafe, ...values]);
            const afterInits = runsEarly ? inInits : unsafe;
            const next = bindings.map(b => keepPos([b[0], walk(b[1], inner, isSingleLambda(b[1]) ? afterInits : inInits)], b));
            const body = e.slice(2).map((x: any) => walk(x, inner, afterInits));
            return liftIn(keepPos([CORE_LETREC, next, ...body], e), scope, afterInits);
        }
        const p = parts(e);
        const next: any[] = [];
        for (const [x, around] of withBounds(p, scope)) next.push(walk(x, around, unsafe));
        return p.rebuild(next);
    };

    const liftIn = (letrec: any[], outer: ReadonlySet<symbol>, unsafe: ReadonlySet<symbol>): any[] => {
        const bindings: [symbol, any][] = letrec[1];
        const body = letrec.slice(2);
        const names = bindings.map(b => b[0]);
        const scope = new Set([...outer, ...names]);
        const inits = new Map<symbol, any>(bindings);
        const within = [...bindings.map(b => b[1]), ...body];

        let lifted = new Set(names.filter(n => isSingleLambda(inits.get(n)) && !assigned.has(n)));
        let fv = new Map<symbol, symbol[]>();
        let calls = new Map<symbol, Uses["calls"]>();
        for (;;) {
            const skip = new Set([...lifted].map(n => inits.get(n)));
            calls = new Map();
            const next = new Set<symbol>();
            for (const name of lifted) {
                const uses = within.reduce((u, x) => usesOf(x, name, skip, new Set(), u), { calls: [], other: false } as Uses);
                if (uses.other || uses.calls.some((c: Uses["calls"][number]) => !accepts(only(inits.get(name)), c.node.length - 1))) continue;
                next.add(name);
                calls.set(name, uses.calls);
            }
            // what each passes: its free locals (lifted ones it calls included), then what those need, to a fixpoint
            fv = new Map([...next].map(name => {
                const c = only(inits.get(name));
                const free = new Set<symbol>();
                for (const x of bodyOf(c)) freeIn(x, scope, new Set(namesOf(c)), free);
                return [name, [...free]];
            }));
            for (let changed = true; changed;) {
                changed = false;
                for (const vars of fv.values()) {
                    for (const v of [...vars]) {
                        for (const w of fv.get(v) ?? []) {
                            if (!vars.includes(w)) {
                                vars.push(w);
                                changed = true;
                            }
                        }
                    }
                }
            }
            // an assigned or not yet known variable cannot be passed, and a call must see the variables it passes as they are here
            for (const name of [...next]) {
                const vars = fv.get(name)!;
                if (vars.some(v => assigned.has(v) || unsafe.has(v)) || calls.get(name)!.some(c => vars.some(v => c.bound.has(v)))) next.delete(name);
            }
            if (next.size === lifted.size) break;
            lifted = next;
        }
        if (lifted.size === 0) return letrec;

        const extra = new Map<any[], symbol[]>();
        for (const name of lifted) for (const c of calls.get(name)!) extra.set(c.node, fv.get(name)!);
        const liftedInit = (name: symbol): any[] => {
            const lambda = inits.get(name);
            const c = only(lambda);
            const vars = fv.get(name)!;
            const renamed = new Map(vars.map(v => [v, Symbol(v.description)]));
            const newBody = bodyOf(c).map((x: any) => rewrite(x, renamed, extra, new Set(namesOf(c))));
            return keepPos([CORE_LAMBDA, clause(optionsOf(c), [...vars.map(v => renamed.get(v)!), ...paramsOf(c)], restOf(c), newBody)], lambda);
        };
        const newBindings = bindings.map(b => keepPos([b[0], lifted.has(b[0]) ? liftedInit(b[0]) : rewrite(b[1], new Map(), extra)], b));
        const newBody = body.map(x => rewrite(x, new Map(), extra));
        return keepPos([CORE_LETREC, newBindings, ...newBody], letrec);
    };

    return walk(ast, new Set(), new Set());
};
